server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: sage-gateway
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost # Or your Redis Cloud URL
      port: 6379
      # timeouts are critical for fail-fast behavior
      timeout: 100ms
      connect-timeout: 200ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


      properties:
        acks: 1
        linger.ms: 10
        batch.size: 16384

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"

resilience4j:
  circuitbreaker:
    instances:
      gatewayService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10              # Look at the last 10 requests
        failureRateThreshold: 50           # If 50% (5 out of 10) fail, trip the breaker!
        waitDurationInOpenState: 15s       # Keep it OPEN (blocking) for 15 seconds
        permittedNumberOfCallsInHalfOpenState: 3 # Let 3 test requests through to check if the API recovered

