server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: sage-gateway
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost # Or your Redis Cloud URL
      port: 6379
      # timeouts are critical for fail-fast behavior
      timeout: 100ms
      connect-timeout: 200ms

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"


